import { opacity as primitiveOpacity, color as primitiveColor } from '../../primitives';

export const ifColors = {
  if: {
    other: {
      a: primitiveColor.neutral['20'],
      b: primitiveColor.neutral['70'],
      c: primitiveColor.adaptive.header.other,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    agibank: {
      a: primitiveColor.sapphire['20'],
      b: primitiveColor.sapphire['60'],
      c: primitiveColor.adaptive.header.agibank,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    banrisul: {
      a: primitiveColor.sapphire['20'],
      b: primitiveColor.sapphire['70'],
      c: primitiveColor.adaptive.header.banrisul,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    bmg: {
      a: primitiveColor.lavender['20'],
      b: primitiveColor.lavender['100'],
      c: primitiveColor.adaptive.header.bmg,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    bradesco: {
      a: primitiveColor.scarlet['20'],
      b: primitiveColor.scarlet['70'],
      c: primitiveColor.adaptive.header.bradesco,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    brb: {
      a: primitiveColor.ocean['20'],
      b: primitiveColor.ocean['110'],
      c: primitiveColor.adaptive.header.brb,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    bb: {
      a: primitiveColor.royalBlue['20'],
      b: primitiveColor.royalBlue['60'],
      c: primitiveColor.adaptive.header.bb,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    btg: {
      a: primitiveColor.sapphire['20'],
      b: primitiveColor.sapphire['100'],
      c: primitiveColor.adaptive.header.btg,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    bv: {
      a: primitiveColor.sapphire['20'],
      b: primitiveColor.sapphire['90'],
      c: primitiveColor.adaptive.header.bv,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    caixa: {
      a: primitiveColor.ocean['20'],
      b: primitiveColor.ocean['90'],
      c: primitiveColor.adaptive.header.caixa,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    caixaTem: {
      a: primitiveColor.ocean['20'],
      b: primitiveColor.ocean['90'],
      c: primitiveColor.adaptive.header.caixaTem,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    c6: {
      a: primitiveColor.neutral['20'],
      b: primitiveColor.neutral['100'],
      c: primitiveColor.adaptive.header.c6,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    citi: {
      a: primitiveColor.sapphire['20'],
      b: primitiveColor.sapphire['60'],
      c: primitiveColor.adaptive.header.citi,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    digio: {
      a: primitiveColor.ocean['20'],
      b: primitiveColor.ocean['120'],
      c: primitiveColor.adaptive.header.digio,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    ebanx: {
      a: primitiveColor.sapphire['20'],
      b: primitiveColor.sapphire['60'],
      c: primitiveColor.adaptive.header.ebanx,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    genial: {
      a: primitiveColor.sapphire['20'],
      b: primitiveColor.sapphire['90'],
      c: primitiveColor.adaptive.header.genial,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    inter: {
      a: primitiveColor.tangerine['20'],
      b: primitiveColor.tangerine['60'],
      c: primitiveColor.adaptive.header.inter,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    itau: {
      a: primitiveColor.tangerine['20'],
      b: primitiveColor.tangerine['70'],
      c: primitiveColor.adaptive.header.itau,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    meliuz: {
      a: primitiveColor.rose['20'],
      b: primitiveColor.rose['40'],
      c: primitiveColor.adaptive.header.meliuz,
      d: primitiveColor.neutral['100'],
      e: primitiveOpacity.color.black['16'],
    },
    mp: {
      a: primitiveColor.yellow['20'],
      b: primitiveColor.yellow['40'],
      c: primitiveColor.adaptive.header.mp,
      d: primitiveColor.neutral['100'],
      e: primitiveOpacity.color.black['16'],
    },
    neon: {
      a: primitiveColor.ocean['20'],
      b: primitiveColor.ocean['60'],
      c: primitiveColor.adaptive.header.neon,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    next: {
      a: primitiveColor.neutral['20'],
      b: primitiveColor.neutral['100'],
      c: primitiveColor.adaptive.header.next,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    noveNove: {
      a: primitiveColor.yellow['20'],
      b: primitiveColor.yellow['50'],
      c: primitiveColor.adaptive.header.noveNove,
      d: primitiveColor.neutral['100'],
      e: primitiveOpacity.color.black['16'],
    },
    nubank: {
      a: primitiveColor.violet['20'],
      b: primitiveColor.violet['80'],
      c: primitiveColor.adaptive.header.nubank,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    original: {
      a: primitiveColor.emerald['20'],
      b: primitiveColor.emerald['60'],
      c: primitiveColor.adaptive.header.original,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    pagB: {
      a: primitiveColor.forestGreen['20'],
      b: primitiveColor.forestGreen['60'],
      c: primitiveColor.adaptive.header.pagB,
      d: primitiveColor.neutral['100'],
      e: primitiveOpacity.color.black['16'],
    },
    pan: {
      a: primitiveColor.sky['20'],
      b: primitiveColor.sky['70'],
      c: primitiveColor.adaptive.header.pan,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    rp: {
      a: primitiveColor.ocean['20'],
      b: primitiveColor.ocean['120'],
      c: primitiveColor.adaptive.header.rp,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    safra: {
      a: primitiveColor.sapphire['20'],
      b: primitiveColor.sapphire['120'],
      c: primitiveColor.adaptive.header.safra,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    santander: {
      a: primitiveColor.scarlet['20'],
      b: primitiveColor.scarlet['60'],
      c: primitiveColor.adaptive.header.santander,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    sicoob: {
      a: primitiveColor.sky['20'],
      b: primitiveColor.sky['120'],
      c: primitiveColor.adaptive.header.sicoob,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    sicredi: {
      a: primitiveColor.forestGreen['20'],
      b: primitiveColor.forestGreen['60'],
      c: primitiveColor.adaptive.header.sicredi,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.black['16'],
    },
    uber: {
      a: primitiveColor.neutral['20'],
      b: primitiveColor.neutral['100'],
      c: primitiveColor.adaptive.header.uber,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
    will: {
      a: primitiveColor.yellow['20'],
      b: primitiveColor.yellow['60'],
      c: primitiveColor.adaptive.header.will,
      d: primitiveColor.neutral['100'],
      e: primitiveOpacity.color.black['16'],
    },
    xp: {
      a: primitiveColor.neutral['20'],
      b: primitiveColor.neutral['100'],
      c: primitiveColor.adaptive.header.xp,
      d: primitiveColor.neutral.white,
      e: primitiveOpacity.color.white['16'],
    },
  },
};

export type IfColors = typeof ifColors;
